---
title: "Topology preservation test"
author: "Francis Lareau"
date: "21/03/2021"
knit: (function(inputFile, encoding) {
  output_dir <- "/Scripts_html";
  if(!dir.exists(output_dir)) {dir.create(output_dir)};
  rmarkdown::render(inputFile, encoding = encoding, output_dir = output_dir) })
output:
  html_document:
    number_sections: false
    toc: yes
    toc_float: true
    theme: united
    highlight: zenburn
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```
   
```{r 1 Librairies}

setwd("your_main_path")

if(!('dplyr' %in% rownames(installed.packages()))){install.packages('dplyr')}
library(dplyr)

if(!('xlsx' %in% rownames(installed.packages()))){install.packages('xlsx')}
library(xlsx)

if(!('readr' %in% rownames(installed.packages()))){install.packages('readr')}
library(readr)

if(!('FactoMineR' %in% rownames(installed.packages()))){install.packages('FactoMineR')}

if(!('vegan' %in% rownames(installed.packages()))){install.packages('vegan')}

if(!('parallelDist'%in% rownames(installed.packages()))){install.packages('parallelDist')}

if(!('stats'%in% rownames(installed.packages()))){install.packages('stats')}

#Function for the topology preservation test
TPT_test <- function(DTM1,DTM2) {
  require(parallelDist)
  require(stats)
  require(vegan)
  require(FactoMineR)
  #Compute DDM (distance)
  DDM1_cos <- parallelDist::parDist(as.matrix(DTM1), method = "cosine", threads = 16) 
  DDM2_cos <- parallelDist::parDist(as.matrix(DTM2), method = "cosine", threads = 16) 
  DDM1_euc <- parallelDist::parDist(as.matrix(DTM1), method = "euclidean", threads = 16)
  DDM2_euc <- parallelDist::parDist(as.matrix(DTM2), method = "euclidean", threads = 16)
  #Compute PCA
  DTM1_pca <- stats::prcomp(DTM1)
  DTM2_pca <- stats::prcomp(DTM2)
  #Mantel test on Cosine distance
  Mantel_cos <- vegan::mantel(DDM1_cos,DDM2_cos, method = 'pearson')
  #Mantel test on Euclidian distance
  Mantel_euc <- vegan::mantel(DDM1_euc,DDM2_euc, method = 'pearson')
  #RV test on cosine distance
  RV_cos <- FactoMineR::coeffRV(as.matrix(DDM1_cos),as.matrix(DDM2_cos))
  #RV test on Euclidian distance
  RV_euc <- FactoMineR::coeffRV(as.matrix(DDM1_euc),as.matrix(DDM2_euc))
  #Procrustes test on PCA
  Procrustes_result <- vegan::protest(DTM1_pca,DTM2_pca)
  return(list('mantel_cos'=Mantel_cos,'mantel_euc'=Mantel_euc,'rv_cos'=RV_cos,'rv_euc'=RV_euc,'pc'=Procrustes_result))
}

```

```{r 2 Topology preservation test for FR}

#RDS encoded DTM import
DTM_trad_fr <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_translation_fr.rds"))
DTM_orig_fr <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_original_fr.rds"))

TPT_test_fr <- TPT_test(DTM_trad_fr,DTM_orig_fr)

```

```{r 3 Topology preservation test for DE}

#RDS encoded DTM import
DTM_trad_de <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_translation_de.rds"))
DTM_orig_de <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_original_de.rds"))

TPT_test_de <- TPT_test(DTM_trad_de,DTM_orig_de)

```

```{r 4 Topology preservation test for NL}

#RDS encoded DTM import
DTM_trad_nl <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_translation_nl.rds"))
DTM_orig_nl <- readRDS(paste0(getwd(),"\\0. Data\\DTM_philosophy_of_science_original_nl.rds"))

TPT_test_nl <- TPT_test(DTM_trad_nl,DTM_orig_nl)

```

```{r 5 Results export}

DF_result <- data.frame(c(nrow(DTM_trad_nl),
                          sum(Matrix::colSums(DTM_orig_nl)!=0),
                          sum(Matrix::colSums(DTM_trad_nl)!=0),
                          TPT_test_nl$mantel_cos$statistic,
                          TPT_test_nl$mantel_cos$signif,
                          TPT_test_nl$mantel_euc$statistic,
                          TPT_test_nl$mantel_euc$signif,
                          TPT_test_nl$rv_cos$rv,
                          TPT_test_nl$rv_cos$p.value,
                          TPT_test_nl$rv_euc$rv,
                          TPT_test_nl$rv_euc$p.value,
                          TPT_test_nl$pc$scale,
                          TPT_test_nl$pc$signif),
                        c(nrow(DTM_trad_de),
                          sum(Matrix::colSums(DTM_orig_de)!=0),
                          sum(Matrix::colSums(DTM_trad_de)!=0),
                          TPT_test_de$mantel_cos$statistic,
                          TPT_test_de$mantel_cos$signif,
                          TPT_test_de$mantel_euc$statistic,
                          TPT_test_de$mantel_euc$signif,
                          TPT_test_de$rv_cos$rv,
                          TPT_test_de$rv_cos$p.value,
                          TPT_test_de$rv_euc$rv,
                          TPT_test_de$rv_euc$p.value,
                          TPT_test_de$pc$scale,
                          TPT_test_de$pc$signif),
                        c(nrow(DTM_trad_fr),
                          sum(Matrix::colSums(DTM_orig_fr)!=0),
                          sum(Matrix::colSums(DTM_trad_fr)!=0),
                          TPT_test_fr$mantel_cos$statistic,
                          TPT_test_fr$mantel_cos$signif,
                          TPT_test_fr$mantel_euc$statistic,
                          TPT_test_fr$mantel_euc$signif,
                          TPT_test_fr$rv_cos$rv,
                          TPT_test_fr$rv_cos$p.value,
                          TPT_test_fr$rv_euc$rv,
                          TPT_test_fr$rv_euc$p.value,
                          TPT_test_fr$pc$scale,
                          TPT_test_fr$pc$signif),
                        row.names = c('Number of articles N(l)',
                                      'Number of termes in the original lexicon M(l)',
                                      'Number of termes in the translated lexicon M*(l)',
                                      'Mantel r on cosine distance',
                                      'Mantel r significance on cosine distance',
                                      'Mantel r on Euclidian distance',
                                      'Mantel r significance on Euclidian distance',
                                      'RV coefficient on cosine distance',
                                      'RV coefficient significance on cosine distance',
                                      'RV coefficient on Euclidean distance',
                                      'RV coefficient significance on Euclidean distance',
                                      'Procrustes correlation on PCA',
                                      'Procrustes correlation significance on PCA'))

colnames(DF_result) <- c('Dutch', 'German','French')

write.xlsx(DF_result, file = paste0(getwd(),"\\3. Topology preservation test\\Results_of_topology_preservation_test.xlsx"), sheetName="Results", row.names=T)

```

